name: Set Commit Status
description: Update commit status for a specific check

inputs:
  state:
    required: true
    description: success | failure | pending
  context:
    required: true
    description: "Name of the status (ex: DOCKER_BUILD)"
  status_description:
    required: false
    default: ""
  target_url:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Update commit status
      shell: bash
      run: |
        curl -L \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -d "{
            \"state\": \"${{ inputs.state }}\",
            \"context\": \"${{ inputs.context }}\",
            \"description\": \"${{ inputs.status_description }}\",
            \"target_url\": \"${{ inputs.target_url }}\"
          }"
      env:
        GITHUB_TOKEN: ${{ github.token }}